skip_docs
desc '[Android] Update App version'
  packageJson = load_json(json_path: "./package.json")
  packageJsonName = packageJson['name']
  packageJsonVersion = packageJson['version']
  gradlePath = './android/app/build.gradle'

  private_lane :inc_ver_android do
    increment_version_code(
      gradle_file_path: gradlePath,
    )

    increment_version_name(
      gradle_file_path: gradlePath,
      version_name: packageJsonVersion
    )
  end

  desc '[iOS] Update App version'
    private_lane :inc_ver_ios do
    packageJson = load_json(json_path: "./package.json")
    packageJsonName = packageJson['name']
    packageJsonVersion = packageJson['version']
    iosProjectPath = './ios/' + packageJsonName + '.xcodeproj'

    increment_build_number(
      xcodeproj: iosProjectPath
    )
    increment_version_number(
      xcodeproj: iosProjectPath,
      version_number: packageJsonVersion
    )
  end

  desc 'Increment build numbers, and set the version to match the pacakage.json version'
  lane :versionUpdate do
    inc_ver_ios
    inc_ver_android
  end
