skip_docs
desc '[Android] Update App version'
  packageJson = load_json(json_path: "./package.json")
  packageJsonName = packageJson['name']
  packageJsonVersion = packageJson['version']
  gradlePath = './android/app/build.gradle'
  androidVersionName = android_get_version_name(
      gradle_file: gradlePath
    )

  private_lane :inc_ver_android do
    if androidVersionName != packageJsonVersion then
        android_set_version_code(
            gradle_file: gradlePath
        )
        
        android_set_version_name(
            version_name: packageJsonVersion,
            gradle_file: gradlePath 
        )
    end
  end

  desc '[iOS] Update App version'
    private_lane :inc_ver_ios do
    packageJson = load_json(json_path: "./package.json")
    packageJsonName = packageJson['name']
    packageJsonVersion = packageJson['version']
    iosProjectPath = './ios/' + packageJsonName + '.xcodeproj'
    iosVersionNumber = get_version_number(
        xcodeproj: iosProjectPath
    )
    if iosVersionNumber != packageJsonVersion then
        increment_build_number(
            xcodeproj: iosProjectPath
        )
    
        increment_version_number(
            xcodeproj: iosProjectPath,
            version_number: packageJsonVersion
        )
    end
  end

  desc 'Increment build numbers, and set the version to match the pacakage.json version'
  lane :versionUpdate do
    inc_ver_android
    inc_ver_ios
  end
