skip_docs
desc "[Android] Update App version"
packageJson = load_json(json_path: "./package.json")
packageJsonName = packageJson["name"]
packageJsonVersion = packageJson["version"]
gradlePath = "./android/app/build.gradle"
androidVersionName = android_get_version_name(
  gradle_file: gradlePath,
)

private_lane :inc_ver_android do
  if androidVersionName != packageJsonVersion
    android_set_version_code(
      gradle_file: gradlePath,
    )

    android_set_version_name(
      version_name: packageJsonVersion,
      gradle_file: gradlePath,
    )
  end
end

desc "[iOS] Update App version"
private_lane :inc_ver_ios do
  packageJson = load_json(json_path: "./package.json")
  packageJsonName = packageJson["name"]
  packageJsonVersion = packageJson["version"]
  iosProjectPath = "./ios/" + packageJsonName + ".xcodeproj"
  iosVersionNumber = get_version_number(
    xcodeproj: iosProjectPath,
  )
  if iosVersionNumber != packageJsonVersion
    increment_build_number(
      xcodeproj: iosProjectPath,
    )

    increment_version_number(
      xcodeproj: iosProjectPath,
      version_number: packageJsonVersion,
    )
  end
end

desc "Increment build numbers, and set the version to match the pacakage.json version"
lane :versionUpdate do
  inc_ver_android
  inc_ver_ios
end

platform :ios do
  private_lane :test_this do
    UI.message "bumping minor"
  end

  lane :release do
    test_this
  end
end

platform :android do
  lane :release do
    yarn(
      command: "install",
    )

    gradle(task: "bundle", build_type: "Release", project_dir: "./android",
           properties: {
             "android.injected.signing.store.file" => "debug.keystore",
             "android.injected.signing.store.password" => "android",
             "android.injected.signing.key.alias" => "androiddebugkey",
             "android.injected.signing.key.password" => "android",
           }, print_command: false)
  end

  lane :codepush do
    yarn(
      command: "install",
    )
    sh("npm install -g appcenter-cli")
    sh("npm install -g @sentry/cli@1.55.1")
    sh("appcenter help")
    sh("sentry-cli --help")
  end
end
