name: Build CSNative

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build: update version') && github.event.head_commit.author.name == 'github-actions[bot]'"
    steps:
      - uses: actions/checkout@v2
      - name: Publish CSNative
        run: echo "Published successfully"

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: actions/checkout@v2
      - name: Get updated packages
        id: updated_packages
        uses: chaitanyadeorukhkar/gh-action-get-changed-files@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a Release
        if: ${{ steps.updated_packages.outputs.updatedVersion!= null }}
        uses: actions/create-release@v1
        with:
          tag_name: "csnative@${{ steps.updated_packages.outputs.updatedVersion }}"
          release_name: "csnative@${{ steps.updated_packages.outputs.updatedVersion }}"
          body: ${{ steps.updated_packages.outputs.updatedChangelogEntry }}
