name: Changeset Check
on:
  pull_request:
    branches: [master]
jobs:
  changeset-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Changed Files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check files
        id: file_check
        run: |
          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"
          $hasChangeset = 0
          for file in ${added_files[@]}; do
            if [[ $file == .changeset* ]]; then
              $hasChangeset = 1
              exit
            fi
          done
          if [[ $hasChangeset == 0 ]]; then
            echo "No Changeset found"
            exit 1
          fi
