name: Slack notifier
# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Changelog Reader
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0
        with:
          path: ./csnative/CHANGELOG.md
      - name: Debug
        run: echo ${{ steps.changelog.outputs.changes }}
