name: Changeset Cheker
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Changed Files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Process files
        id: check
        run: |
          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"
          for file in ${added_files[@]}; do
            if [[ $file != .changeset* ]]; then
              echo "::set-output name=hasChangeset::1"
              exit
            fi
          done
          echo "::set-output name=hasChangeset::0"
      - name: Debug
        env: 
          CHANGED_FILES: ${{ steps.changed_files.outputs.all }}
        run: echo $CHANGED_FILES
      - name: No Changeset Found
        if: steps.check.outputs.hasChangeset == 0
        run: echo "No Changeset found. Please add a Changeset to your PR." ; exit 1
      - name: Changeset Found
        if: steps.check.outputs.hasChangeset == 1
        run: echo "Changeset Found!"
