name: Event Test

on:
  push:
    branches: [ master ]

jobs:
  create_tags:
    if: "contains(github.event.head_commit.message, 'build: update version') && github.event.head_commit.author.name == 'github-actions[bot]'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run echo
        run: echo "THIS IS A VERSION COMMIT!!!"

