name: Slack notifier
# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Markdown Converter
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        id: convert
        with:
          text: cat csnative/CHANGELOG.md
      - name: Debug
        run: echo ${{ steps.convert.outputs.text }}
