name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: macos-10.15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Set yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.58.1
        with:
          ruby-version: 2.7

      - name: Setup Fastlane
        run: bundle install

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn version-update
          commit: "build: update version"
          title: "build: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_tags:
    if: "contains(github.event.head_commit.message, 'build: update version') && github.event.head_commit.author.name == 'github-actions[bot]'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read changelog
        id: changelog
        uses: chaitanyadeorukhkar/changelog-reader-action@master
      - name: Echo version
        run: echo ${{ steps.changelog.outputs.version }}
