name: Release

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: csnative

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn version
          commit: "build: update version"
          title: "buildg: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
