name: Release

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: csnative

jobs:
  release:
    name: Release
    runs-on: macos-10.15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.58.1
        with:
          ruby-version: 2.7

      - name: Setup Fastlane
        run: bundle install

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn version-update
          commit: "build: update version"
          title: "build: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
