name: Version

on:
  push:
    branches:
      - master

jobs:
  changeset_version:
    name: Update Version
    runs-on: macos-10.15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Set yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Ruby dependencies
        uses: actions/cache@v1
        with:
          path: ~/.bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.58.1
        with:
          ruby-version: 2.7

      - name: Setup Fastlane
        run: bundle install

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          version: yarn version-update
          commit: "build: update version"
          title: "build: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Releases
        if: "contains(github.event.head_commit.message, 'build: update version') && github.event.head_commit.author.name == 'github-actions[bot]'"
        run: yarn create-release ${{ secrets.GITHUB_TOKEN }}
